version: '3.8'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data_fs:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - static_volume_fs:/home/app/web/static
      - media_volume_fs:/home/app/web/media
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000 --workers 3

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
     - ./nginx:/etc/nginx/templates
     - static_volume_fs:/home/app/web/static
     - media_volume_fs:/home/app/web/media
    ports:
     - "1335:80"
    environment:
     - NGINX_PORT=80
    depends_on:
      - web

volumes:
  postgres_data_fs:
  static_volume_fs:
  media_volume_fs: